#
# Test Vagrant server environment (base box development platform)
#-------------------------------------------------------------------------------
#
Vagrant.configure('2') do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "coralnexus/ubuntu-14.04-server-amd64"
  
  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :private_network, :ip =>"172.40.30.20"
end
